version: '3'
services:
  db:
    image: mysql:latest
    container_name: StarFoodDBProduction
    ports:
      - "3306:3306"
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: StArFoOdDb
      MYSQL_DATABASE: StarFoodDB

  webapi:
    image: starfood:1.0
    container_name: StarFoodWebAPI
    ports:
      - "443:5000"
    depends_on:
      - db